### ISSUE TITLE
CLI: Remap types passed to CLI print

### ISSUE THREAD

**Issue by Billy99** [bpfman/bpfman#1009]
Originally, CLI code sent an RPC request to bpfman. For Get/List/Create commands, bpfman returns a `command::Program` (see [command.rs](https://github.com/bpfman/bpfman/blob/main/bpfman/src/command.rs#L201)), which then gets mapped into the API structure used by RPC, `bpfman_api::v1::ProgramInfo` and `bpfman_api::v1::KernelProgramInfo` (see [bpfman.v1.rs](https://github.com/bpfman/bpfman/blob/main/bpfman-api/src/bpfman.v1.rs#L35)) and passed to `ProgTable`(see [table.rs](https://github.com/bpfman/bpfman/blob/main/bpfman/src/cli/table.rs#L19)) to be printed.

`ProgTable` can be rewritten to take `command::Program` instead, skipping the mapping from `command::Program` to `bpfman_api::v1::ProgramInfo` and `bpfman_api::v1::KernelProgramInfo`.

**Comment by astoycos** [comment]
cc @msherif1234 this may be a good place to start

**Comment by astoycos** [comment]
I unfortunately had to pick this up in #1014
