### ISSUE TITLE
Deprecate the TC dispatcher in favor of the new TCX link type

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#1016]
The new [TXC feature](https://lore.kernel.org/all/20230719140858.13224-1-daniel@iogearbox.net/) will allow users to more easily control the priority between various TC programs, and is now part of the mainstream kernel.  We should hop on this bandwagon and use the TCX infrastructure to maintain priority ordering between TC programs we maintain rather than maintaining a custom dispatcher.

This will require us to add TCX support to aya first! (see https://github.com/cilium/ebpf/issues/1117 for an example)

**Comment by anfredette** [comment]
Is this what we want, or do we want to continue to support both TC and TCX?

**Comment by anfredette** [comment]
We will continue to support both TC and TCX.
