### ISSUE TITLE
Use "//go:generate go run github.com/cilium/ebpf/cmd/bpf2go ..." instead of just "//go:generate bpf2go ..."

### ISSUE THREAD

**Issue by thediveo** [bpfman/bpfman#1080]
In its examples, [`@cilium/ebpf`](https://github.com/cilium/ebpf) uses

```go
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go ...
```

instead of just 

```go
//go:generate bpf2go ...
```

The rationale is that this does automatically pull and build bpf2go without the user having to explicitly install the tool first.

This allows for the Go-idiomatic way to get the example up and running without much ado:

```bash
cd examples/go-xdp-counter
go generate . # generate eBPF .o
go run -exec sudo . -iface ens33
```

**Comment by thediveo** [comment]
Ah, the nudge 😁 ... can work on a PR. I could tackle both examples and the associated description for the bpfman.io, if that's okay?

Juwt to clarify one aspect here: based on the system.d configuration I assume access rights `0660` for the `bpfman.sock`: if this assumption is correct, then I'll update the docs in the PR to correctly reflect the need of `-exec sudo` when runningnthe Go examples.

Off tangent: could you please rename `bpfman`, as I'm constantly mistyping it as `pdfman`, please?

**Comment by astoycos** [comment]
> Ah, the nudge 😁 ... can work on a PR. I could tackle both examples and the associated description for the bpfman.io, if that's okay?

Ahaha all good I was just triaging :) If you want to snag it I wouldn't stop you though! 

> Just to clarify one aspect here: based on the system.d configuration I assume access rights 0660 for the bpfman.sock: if this assumption is correct, then I'll update the docs in the PR to correctly reflect the need of -exec sudo when running the Go examples.

Correct! That brings up a good point though....and maybe another issue? I think it would be cool to make it possible to run the example programs on the host without root privs... @Billy99 We used to have the bpfman user group (but don't anymore) do we bring that back? 

> Off tangent: could you please rename bpfman, as I'm constantly mistyping it as pdfman, please?

LOL We're still reeling from the [most recent name change](https://bpfman.io/v0.4.0/blog/2023/11/23/bpfd-becomes-bpfman/)  😉

**Comment by thediveo** [comment]
> Correct! That brings up a good point though....and maybe another issue? I think it would be cool to make it possible to run the example programs on the host without root privs... @Billy99 We used to have the bpfman user group (but don't anymore) do we bring that back?

My preliminary understanding is that we would need either an additional access management, or otherwise, similar to other use cases incl. Docker, create and assign a dedicated user group. The user trying out the examples then would need to be a member of this group to be allowed to connect to the API socket. This of course complicates the examples, but would otherwise ensure a decent setup.

**Comment by Silvanoc** [comment]
> My preliminary understanding is that we would need either an additional access management, or otherwise, similar to other use cases incl. Docker, create and assign a dedicated user group. The user trying out the examples then would need to be a member of this group to be allowed to connect to the API socket. This of course complicates the examples, but would otherwise ensure a decent setup.

I'm not that sure that it's a more decent setup than requiring root rights. More convenient, without doubt. 

My concern is that bpfman might reproduce Docker's errors (lack of awareness about the powers acquired by a Docker user):
* Being able to load and attach eBPF programs gives you a close-to-root power and that is not clear enough to many people.
* Forcing people to get root-rights keep people aware of the high powers they are getting.
* If using a group to grant those powers, the risks should be crystal clear documented.

**Comment by thediveo** [comment]
original issue fixed ... @Silvanoc no changes to the API socket access, do we need to document this somehow and in case can you please file a new dedicated documentation issue?
