### ISSUE TITLE
Setup packit to ensure we publish official RPM builds for each release 

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#1081]
Today packit builds dev RPMS based on our main, we need to ensure that they're also built on our releases and stored somewhere.

**Comment by thediveo** [comment]
Could you please also provide .deb packages?

**Comment by astoycos** [comment]
@astoycos Make a new issue tracking .deb package support

**Comment by astoycos** [comment]
This was completed via https://github.com/bpfman/bpfman/pull/1114
