### ISSUE TITLE
Update the OCI image spec used for packaging ebpf bytecode

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#1090]
- Package both el/eb variants of BPF bytecode in an eBPF OCI image
- Determine if there's any existing OCI specific infrastructure that can help us here
- It would be great if this worked the same way as multi-arch manifests (i.e we have a meta manifest that points to the actual image manifests for the correct os/arch)

**Comment by Billy99** [comment]
Addressed with #1141
