### ISSUE TITLE
bpfman-rpc fails with SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by Silvanoc** [bpfman/bpfman#1094]
I'm trying to test bfpman from [release image](https://bpfman.io/v0.4.0/getting-started/running-release/)  and I'm getting a hard to debug error on bpfman-rpc: **Illegal instruction (SIGILL)**.

I'm starting (as root) bpfman-rpc with all the possible arguments to get some information: `RUST_BACKTRACE=1 RUST_LOG=debug ./bpfman-rpc --timeout=0`. But I see no output at all, therefore I liked issue #1078.

I then try to run one of the examples (also as root): `./go-tc-counter -direction ingress -iface eth0`.
It first reports how it's being run:
```2024/04/16 16:32:24 Using Input: Interface=eth0 Priority=50 Source=/home/[...]/repos/github/bpfman/bpfman/examples/go-tc-counter/bpf_bpfel.o```
I then get the only output I get from **bpfman-rcp**:
```Illegal instruction```
And straight away an RPC error on the example:
```2024/04/16 16:32:25 rpc error: code = Unavailable desc = error reading from server: EOF```

Any idea what's going on? Or how to better diagnose it?

Running on Ubuntu 23.10 (Mantic) here.

**Comment by Billy99** [comment]
I'll try to reproduce, Thanks for creating the issue.

**Comment by Billy99** [comment]
Sorry for all the issues you are hitting.

Your comment: "But I see no output at all, ..." was hopefully fixed by #1082, which fixed your the original issue you wrote, #1077. That fixed two issues, logs not being output because the logger wasn't initialized in `bpfman-rpc`, and the socket directory not being created. You will need that fix to continue. I assume you pulled that PR in, otherwise `./bpfman-rpc --timeout=0` returns `Error: No such file or directory (os error 2)` and stops. Can you confirm that?

We are working on a 0.4.1 release, which we hope to cut soon. You may be better off working from main if that is possible.

I repeated your steps based on main (so I had the above fixes) and didn't reproduce. What OS and kernel did you see the `Illegal instruction` on? I was testing on Fedora 39. I did a search for Fedora illegal instruction and came across this recent issue: https://discussion.fedoraproject.org/t/many-programs-crash-with-illegal-instruction-core-dumped/110509, not sure if it's related.

**Comment by Silvanoc** [comment]
> Sorry for all the issues you are hitting.

No big deal. That's what OSS collaboration is what for 🙂 If I find an issue, I report it.

> Your comment: "But I see no output at all, ..." was hopefully fixed by https://github.com/bpfman/bpfman/pull/1082, which fixed your the original issue you wrote, https://github.com/bpfman/bpfman/issues/1077. That fixed two issues, logs not being output because the logger wasn't initialized in bpfman-rpc, and the socket directory not being created. You will need that fix to continue. I assume you pulled that PR in, otherwise ./bpfman-rpc --timeout=0 returns Error: No such file or directory (os error 2) and stops. Can you confirm that?

I was having difficulties to build from main on my VM (OOM), that's why I simply created /run/bpfman-sock directory to get the released version running.

> We are working on a 0.4.1 release, which we hope to cut soon. You may be better off working from main if that is possible.

I've been finally able to get it built with the command  `CARGO_PROFILE_RELEASE_LTO=off cargo build --release`, but no `bpfman-rpc` is being built, so I cannot test it from main. This has probably the same root cause as #1095. 

> I repeated your steps based on main (so I had the above fixes) and didn't reproduce. What OS and kernel did you see the Illegal instruction on? I was testing on Fedora 39. I did a search for Fedora illegal instruction and came across this recent issue: https://discussion.fedoraproject.org/t/many-programs-crash-with-illegal-instruction-core-dumped/110509, not sure if it's related.

Sorry, forgot to report it. I'm using Ubuntu 23.10 (Mantic). I'll add it to the issue description.

**Comment by Billy99** [comment]
I created an Ubuntu 23.10 VM and loaded the release binary and it worked fine. Similar to the other link I posted: https://users.rust-lang.org/t/illegal-instruction-when-running-release-build-on-ubuntu-vm/97455/6  We may be building for a higher end machine and your VM doesn't have all the CPU flags binary was built for. Can you post a `cat proc/cpuinfo` for one of the CPUs and maybe something will stand out when I compare it to mine.

`flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat vnmi umip flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid shadow_vmcs pml
`

**Comment by Silvanoc** [comment]
@Billy99 these are the flags of my VM CPU:
`flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm rep_good nopl cpuid extd_apicid pni cx16 hypervisor lahf_lm cmp_legacy svm 3dnowprefetch vmmcall`

Your flags list looks a bit weird, there are two `flags:` entries.

**Comment by Silvanoc** [comment]
I've been able to reproduce this issue on a Fedora VM where I'm installing bpfman v0.4.1 with dnf.

CPU flags are the same, that might be the root-cause... But which one?

@Billy99 could you please run the same command as me (`cat /proc/cpuinfo|grep "^flags"|uniq|cut -d ':' -f 2|sort|tr ' ' '\n'|sort|tr '\n' ' '`) to get a set that is easy to compare? Thanks!

**Comment by Silvanoc** [comment]
Got it working! I have not been able to pin the issue down to a specific CPU flag, but at least I found out that using "Haswell" emulation it works.

Just in case you are interested on further investigations, I am providing here the flags comparison between the set of CPU flags of QEMU Haswell emulation (working and shorter than yours) and that one provoking the issue:
```diff
-abm
-aes
+3dnowprefetch
 apic
-arat
-avx
-avx2
-bmi1
-bmi2
 clflush
 cmov
-constant_tsc
+cmp_legacy
 cpuid
 cx16
 cx8
 de
-erms
-f16c
-fma
+extd_apicid
 fpu
-fsgsbase
 fxsr
 ht
 hypervisor
@@ -27,33 +17,21 @@
 mca
 mce
 mmx
-movbe
 msr
 mtrr
 nopl
 nx
 pae
 pat
-pclmulqdq
 pge
 pni
-popcnt
 pse
 pse36
-pti
-rdrand
-rdtscp
 rep_good
 sep
-smep
 sse
 sse2
-sse4_1
-sse4_2
-ssse3
+svm
 syscall
 tsc
-x2apic
-xsave
-xsaveopt
-xtopology
+vmmcall
```

**Comment by Silvanoc** [comment]
Knowing that "Haswell" CPU-emulation works, I'm closing this issue.

Please feel free to reopen it, if you want to further diagnose it yourself.

**Comment by Silvanoc** [comment]
You might want to document it for others trying to test it on a VM.

**Comment by Silvanoc** [comment]
Got it! The missing CPU flag was `rdtscp`. Using QEMU the CPU specification `qemu64` + `rdtscp` works.

**Comment by Billy99** [comment]
Thank you @Silvanoc for hunting down the missing CPU flag. I'll add to the docs.
