### ISSUE TITLE
FEDORA PACKAGING: Accidentally skipping all tests:

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#1132]
The way you've split the "--skip" arguments for "%cargo_test" across multiple lines interferes with RPM's macro expansion. Using escaped newlines accidentally causes *no* tests to be run *at all*. I'm not sure why, but it's a known problem. Even if long lines like it are ugly, you will need to keep all arguments for %cargo_test on a single line for them to work correctly (and not accidentally disabling *all* tests, not only the ones explicitly mentioned).

**Comment by danielmellado** [comment]
This is already fixed ;)
