### ISSUE TITLE
bytecodeError hard to debug

### ISSUE THREAD

**Issue by vsoch** [bpfman/bpfman#1143]
Hi! I'm having a really hard time getting started using your library. I ran the examples OK, but when I modify the code a little bit to be abount counting sys_execve, no matter what I do, I get a bytecodeerror

```
Name:         go-kprobe-counter-example-kind-control-plane-try-to-wake-up
Namespace:    
Labels:       bpfman.io/ownedByProgram=go-kprobe-counter-example
              kubernetes.io/hostname=kind-control-plane
Annotations:  bpfman.io.kprobeprogramcontroller/function: try_to_wake_up
API Version:  bpfman.io/v1alpha1
Kind:         BpfProgram
Metadata:
  Creation Timestamp:  2024-05-19T17:53:50Z
  Finalizers:
    bpfman.io.kprobeprogramcontroller/finalizer
  Generation:  1
  Owner References:
    API Version:           bpfman.io/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  KprobeProgram
    Name:                  go-kprobe-counter-example
    UID:                   1e053e67-25ea-40eb-ab43-c145840a9ffc
  Resource Version:        1621
  UID:                     43e34728-7303-4e89-bf9f-74254a8914df
Spec:
  Type:  kprobe
Status:
  Conditions:
    Last Transition Time:  2024-05-19T17:53:50Z
    Message:               There was an error processing the provided bytecode selector
    Reason:                bytecodeSelectorError
    Status:                True
    Type:                  BytecodeSelectorError
Events:                    <none>
```
I don't know how to debug this or where to start - the operator and daemon offer no error messages that are useful. I was trying to take examples from cilium https://github.com/cilium/ebpf/tree/main/examples and replace with what you have, and the main difference seems to be having additional headers included (could that be an issue)? 

Can you give some tips? Thanks!

**Comment by anfredette** [comment]
@vsoch, Thanks for your question.

I think what's happening is the [GetBytecode()](https://github.com/anfredette/bpfman/blob/d826b70ac40d88431e6c66b7eff160dd69ed2f8a/bpfman-operator/controllers/bpfman-agent/internal/bpfman-core.go#L49) function is returning an error.  I suspect it's a problem with the format of the name of the image or bytecode file you are using.

If that's not enough help, I'll need some more info.  Could you share a diff of the changes you've made, or push your changes to your personal repo and share them so I could take a look?

**Comment by vsoch** [comment]
Done!

https://github.com/rse-ops/ebpf-hpc-examples/tree/main/examples/sys_execve

And thank you so much - I really appreciate the help, I'm totally new to doing this. I think I might have found something when I was preparing that README - something about a repository name that needs to be canonical? And it's receiving a func() string instead? 

```console
{"level":"error","ts":"2024-05-20T20:39:28Z","logger":"kprobe","msg":"Reconciling program failed","Program NameError":"json: unsupported type: func() string","ReconcileResult":"Updated","error":"failed to reconcile bpfman program: failed to process bytecode selector: repository name must be canonical","stacktrace":"github.com/bpfman/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon\n\t/usr/src/bpfman/bpfman-operator/controllers/bpfman-agent/common.go:148\ngithub.com/bpfman/bpfman/bpfman-operator/controllers/bpfman-agent.(*KprobeProgramReconciler).Reconcile\n\t/usr/src/bpfman/bpfman-operator/controllers/bpfman-agent/kprobe-program.go:163\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}
```

I suspect I did something wrong in the main code, so if you have a quick set of eyes to see if I'd really appreciate it. Thanks again for your help!

**Comment by anfredette** [comment]
Wherever you specify an image, it needs to be a proper url to a repo that contains the image.  For example: 
```
quay.io/bpfman-userspace/go-kprobe-counter:latest
```
In our examples, we use kustomize to update the image names in the yaml files, so that may not be clear.

I think the code is erroring on the following info:
https://github.com/rse-ops/ebpf-hpc-examples/blob/main/examples/sys_execve/ebpf.yaml#L80

The following probably won't work either:
https://github.com/rse-ops/ebpf-hpc-examples/blob/main/examples/sys_execve/ebpf.yaml#L34

Also, you'll need to build the images, push them to the repo, and then make the repo public.  We can also work with a private repo, but that takes a few more steps to set up a secret to use.  You can see how we build and push the images in the [Makefile](https://github.com/bpfman/bpfman/blob/main/examples/Makefile) and also [build-bytecode-images.sh](https://github.com/bpfman/bpfman/blob/main/examples/build-bytecode-images.sh) for building the bytecode images.

Let me know if that helps.

**Comment by vsoch** [comment]
Ak! That's a rookie mistake, of course images for Kubernetes need to exist (I'm surprised it didn't tell me that as the error). If you follow the README I was loading them into kind, and for some reason forgot the ghcr.io.

I added it, and now I see that the name of the bpf program is made really long, and it's expecting a shorter one.

```
Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    50s               default-scheduler  Successfully assigned go-kprobe-counter/go-kprobe-counter-ds-vcrkq to kind-control-plane
  Warning  FailedMount  8s (x7 over 41s)  kubelet            MountVolume.SetUp failed for volume "go-kprobe-counter-maps" : rpc error: code = NotFound desc = Bpfman Program go-kprobe-counter-example not found
vanessa@vanessa-ThinkPad-T14-Gen-4:~/Desktop/Code/ebpf-hpc$ kubectl get bpfprograms.bpfman.io 
NAME                                                          TYPE     STATUS            AGE
go-kprobe-counter-example-kind-control-plane-try-to-wake-up   kprobe   bpfmanNotLoaded   66s
```
Is that name derived programatically and why is it so long?

**Comment by vsoch** [comment]
Ah I see- you really do need it to push to get the manifest.

```
Cannot fetch manifest of ghcr.io/rse-ops/ebpf-hpc-examples:sys_execv-bytecode:
```

**Comment by vsoch** [comment]
Making progress! It was able to load, and now this appears to be issues with my code (not surprising) :laughing: 

```console

  ----     ------       ----               ----               -------
  Normal   Scheduled    70s                default-scheduler  Successfully assigned go-kprobe-counter/go-kprobe-counter-ds-ljp6d to kind-control-plane
  Warning  FailedMount  28s (x7 over 60s)  kubelet            MountVolume.SetUp failed for volume "go-kprobe-counter-maps" : rpc error: code = NotFound desc = map kprobe_stats_map not found in go-kprobe-counter-example's pinned maps: `BPF_OBJ_GET` failed
```

**Comment by anfredette** [comment]
@vsoch, It's been a while.  Were you able to get this working?

**Comment by vsoch** [comment]
hey @anfredette ! I wound up stepping back and I'm writing little eBPF programs on a VM to monitor containers - I am planning to start that way and then move to Kubernetes. Feel free to close the issue if you like - I'll get back to this but not for some time. I can always open a new one.

**Comment by anfredette** [comment]
Sounds good.  Let us know if you need anything when you get back to bpfman.
