### ISSUE TITLE
RPM Build Failures for bpfman v0.5.2

### ISSUE THREAD

**Issue by anfredette** [bpfman/bpfman#1303]
The builds for F39 and F40 succeeded, but F41 and rawhide failed with the following error:

```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
*** ERROR: ./usr/src/debug/bpfman-0.5.2-1.fc41.x86_64/vendor/typed-path/src/lib.rs has shebang which doesn't start with '/' ([cfg_attr(feature = "std", doc = include_str!("../README.md"))])

RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.51Gkr8 (%install)
    Bad exit status from /var/tmp/rpm-tmp.51Gkr8 (%install)
```

**Comment by danielmellado** [comment]
This seems to be coming from the brp-mangle-shebangs script running on the library as it's marked as an executable. I've submitted a PR to it in order to change. https://github.com/chipsenkbeil/typed-path/pull/33

Will also check a workaround for us for the time being.
