### ISSUE TITLE
Ensure the linux capabilities are set properly in k8s deployment

### ISSUE THREAD

**Issue by Billy99** [bpfman/bpfman#167]
When bpfd is launch in k8s using the sample yaml in `packaging/kubernetes-deployment/', update the yaml files to manage the linux capabilities the same as when running bpfd as a systemd service.

**Comment by astoycos** [comment]
Started in https://github.com/bpfd-dev/bpfd/pull/737

**Comment by dave-tucker** [comment]
Closing since our plan is `bpfman` on the host, used via socket activation. Therefore bpfman will be privileged but will only be active for a short time.
