### ISSUE TITLE
Add predicate support to the bpfd `list` API

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#225]
Currently the bpfd list API only supports the listing of ALL programs which bpfd is managing.  This issue will track the work of adding the ability to list a specific set of programs by their traits... I.e Attachment Point, Program type, Priority etc.

**Comment by anfredette** [comment]
We also need to sort them in a reasonable way.  In fact, sorting by the traits you mentioned above sounds good to me.

**Comment by astoycos** [comment]
Blocked on #340 

Ultimately though in the API we'll be able to query via `program_type` and then the rest will need to get done via client side filtering.

**Comment by dave-tucker** [comment]
This is already implemented via the `bpfman list --metadata-selector`.
Closing as completed.
