### ISSUE TITLE
Update or remove kubectl-bpfprogramconfigs and kubectl-bpfprograms

### ISSUE THREAD

**Issue by anfredette** [bpfman/bpfman#631]
Do we still need https://github.com/bpfd-dev/bpfd/blob/main/bpfd-operator/hack/kubectl-bpfprogramconfigs and https://github.com/bpfd-dev/bpfd/blob/main/bpfd-operator/hack/kubectl-bpfprograms 

If so, update them based on the latest changes.

**Comment by astoycos** [comment]
That's a question for @Billy99

**Comment by anfredette** [comment]
I had mentioned it to @Billy99 and he requested that I open an issue.

One more thought I've had is that it would be good to have a nicely formatted summary listing via `kubectl` -- kind of like what we get from `bpfctl list`.
