### ISSUE TITLE
Possibility of a Rustconf 2024 Talk for bpfman

### ISSUE THREAD

**Issue by shaneutt** [bpfman/bpfman#859]
We had good success [talking about bpfman at Kubecon](https://www.youtube.com/watch?v=8pXBbFzH_tQ), which was very relevant there because of our Kubernetes operator and the general additional security problems we want to help with in Kubernetes ecosystems.

The purpose of this task is to suggest that perhaps we could put together a bpfman talk for [Rustconf](https://rustconf.com/) 2024 (which isn't fully announced at the time of writing, but should be somewhere around September).

We discussed this in the community call, and we felt that the audience there is going to be particularly interested in our _development_ experience and using Rust for this technology (as opposed to being interested in Kubernetes operators, e.t.c.) so we think there are some good focus areas we could use in a talk:

* bpfman under the hood
  * what rust tools, libraries we use
    * general talk about Aya
      * the history of eBPF in Rust, from RedBPF to Aya
      * the current experience, benefits, and difficulties of writing eBPF code in Rust
   * our container image delivery and verification system
* using Rust to build a Kubernetes operator (maybe: we've been talking about going back to Rust for the operator but it's not done yet, maybe it would be done in time for Rustconf)

**Comment by astoycos** [comment]
I'm working on this will document in https://docs.google.com/document/d/17oq1IqSjvbPDcQMNceRGQyHakN-TOhbtYQK6lMU_u6k/edit?usp=sharing

**Comment by shaneutt** [comment]
(talk did not get accepted!)
