### ISSUE TITLE
Make all sled-db keys `const`'s

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#912]
Now that we're focusing on sled database there's a number of get and set operations we maintain similar to the following:

```
    pub(crate) fn set_name(&mut self, name: &str) -> Result<(), BpfmanError> {
        sled_insert(&self.db_tree, "name", name.as_bytes())
    }

    pub(crate) fn get_name(&self) -> Result<String, BpfmanError> {
        sled_get(&self.db_tree, "name").map(|v| bytes_to_string(&v))
    }
```

All of these keys should be turned into rust `const` variables to avoid typos in set/get functions!

**Comment by shawnh2** [comment]
hi, interested in picking this one up, please assign
