### ISSUE TITLE
Make CSI plugin it's own binary

### ISSUE THREAD

**Issue by dave-tucker** [bpfman/bpfman#932]

**Comment by astoycos** [comment]
Putting this on the backburner for the moment, waiting to see all of the GRPC stuff removed first for the core suite of functionality at least.

**Comment by astoycos** [comment]
Now that the RPC server along with the CSI plugin has been moved into it's own process I'm not 100% sure we will end up going this route, I'll bring it up in the next community meeting

**Comment by astoycos** [comment]
Closing this since the both rpc servers (CSI AND bpfman API) can just live in the bpfman-rpc binary
